### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by rcass** [edwardlanto/Aloha-Homepage-Project#3]
There are some small CSS fixes to be made.

- [x] .nav-logo can be removed from style.css since there are declarations inside. 

- [x] In style.css, towards the bottom of the style sheet there is a lot of unnecessary whitespace. Be consistent with your CSS formatting and remove these extra spacing.

- [x] The last media query is missing the closing curly brace.

- [x] You still haven’t implemented the @font-face trick for avoiding faux italics and bolding. Please implement as directed [here](https://www.metaltoad.com/blog/how-use-font-face-avoid-faux-italic-and-bold-browser-styles)

- [x] Mobile still needs work to look like the design. In mobile, the hero banner background images do not match the design. Adjust those background properties. 

- [x] Typography does not match the design, there are many areas where the font-face does not match the design. Please go back and compare your site to the design files.

- [x] Font sizes and line height do not match the design especially in Mobile. Most of the of fonts are too large. For example, "hand crafted styles" and the paragraph below do not match the design. 

- [x] The width of the content sections do not match the design. This is really obvious in desktop view where it is much wider than the given designs.

**Comment by edwardlanto** [comment]
Finished all issues, please review when you have time.
